--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/PlayerVaults
branches:
- master
- dev
projects:
  PlayerVaults:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: 2.0.0
...
