--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/PlayerVaults
branches:
- master
- patch-5
projects:
  PlayerVaults:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^2.0.1
      - src: poggit/libasynql/libasynql
        version: ^3.1.1
...
